plugins {
    id 'java'
}

allprojects {
    group = "git.immutable.kombat"
    version = "2025.0312.01"
    description = "Premium Minecraft combat plugin with 1.8 PvP mechanics"
}

subprojects {
    apply plugin: 'java'

    java {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    repositories {
        mavenCentral()

        maven {
            name = "papermc-repo"
            url = "https://repo.papermc.io/repository/maven-public/"
        }
        maven {
            url "https://repo.okaeri.cloud/releases/"
        }
    }

    dependencies {
        implementation 'eu.okaeri:okaeri-configs-yaml-bukkit:6.0.0-beta.23'
        implementation("net.kyori:adventure-api:4.25.0")
        compileOnly("org.projectlombok:lombok:1.18.42")
        annotationProcessor("org.projectlombok:lombok:1.18.42")
    }

    tasks.withType(JavaCompile) {
        options.encoding = 'UTF-8'
        options.compilerArgs << '-parameters'
    }

    test {
        useJUnitPlatform()
    }
}